{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "c22cdfe1-4d79-42be-951b-b5f2e010bdd9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda\\Lib\\tkinter\\__init__.py\", line 1968, in __call__\n",
      "    return self.func(*args)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_32276\\3780326631.py\", line 7, in data_get\n",
      "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
      "           ^^^^^^^\n",
      "NameError: name 'request' is not defined. Did you mean: 'requests'?\n"
     ]
    }
   ],
   "source": [
    "from tkinter import*\n",
    "from tkinter import  ttk\n",
    "import  requests\n",
    "\n",
    "def data_get():\n",
    "    city = city_name.get()\n",
    "    data = request.get(\"https://api.openweathermap.org/data/2.5/weather?q=\"+city+\"&appid=3d15ee8d1abc1b58ec14e770984d3fa0\").json()\n",
    "    w_label1.config(text=data[\"weather\"][0][\"main\"])\n",
    "    wb_label1.config(text=data[\"weather\"][0][\"discription\"])\n",
    "    temp_label1.config(text=str(data[\"main\"][\"temp\"]-273.15))\n",
    "    ppr_label1.config(text=data[\"main\"][\"pressure\"])   \n",
    "\n",
    "\n",
    "\n",
    "win = Tk()\n",
    "win.title(\"Adwait Choudhari\")\n",
    "win.config(bg = \"blue\")\n",
    "win.geometry(\"500x570\")\n",
    "\n",
    "name_label = Label(win,text=\"Adwait's Weather App\",\n",
    "                   font=(\"Time New Roman\",30,\"bold\"))\n",
    "name_label.place(x=25,y=50,height=50,width=450)\n",
    "\n",
    "\n",
    "city_name = StringVar()\n",
    "list_name = [\"Andhra Pradesh\",\"Arunachal Pradesh \",\"Assam\",\"Bihar\",\"Chhattisgarh\",\"Goa\",\"Gujarat\",\"Haryana\",\"Himachal Pradesh\",\"Jammu and Kashmir\",\"Jharkhand\",\"Karnataka\",\"Kerala\",\"Madhya Pradesh\",\"Maharashtra\",\"Manipur\",\"Meghalaya\",\"Mizoram\",\"Nagaland\",\"Odisha\",\"Punjab\",\"Rajasthan\",\"Sikkim\",\"Tamil Nadu\",\"Telangana\",\"Tripura\",\"Uttar Pradesh\",\"Uttarakhand\",\"West Bengal\",\"Andaman and Nicobar Islands\",\"Chandigarh\",\"Dadra and Nagar Haveli\",\"Daman and Diu\",\"Lakshadweep\",\"National Capital Territory of Delhi\",\"Puducherry\"] \n",
    "com = ttk.Combobox(win,text=\"Adwait's Weather App\",values=list_name,\n",
    "                   font=(\"Time New Roman\",20,\"bold\"),textvariable=city_name)\n",
    "com.place(x=25,y=120,height=50,width=450)\n",
    "\n",
    "\n",
    "#1-------------------------------------------------------------------------------------------\n",
    "w_label = Label(win,text=\"Weather Climate\",\n",
    "                   font=(\"Time New Roman\",20,))\n",
    "w_label.place(x=25,y=260,height=50,width=210)\n",
    "\n",
    "\n",
    "w_label1 = Label(win,text=\"\",\n",
    "                   font=(\"Time New Roman\",20,))\n",
    "w_label1.place(x=250,y=260,height=50,width=210)\n",
    "\n",
    "#2-----------------------------------------------------------------------------------------\n",
    "wb_label = Label(win,text=\"Weather Discription\",\n",
    "                   font=(\"Time New Roman\",17,))\n",
    "wb_label.place(x=25,y=330,height=50,width=210)\n",
    "\n",
    "wb_label1 = Label(win,text=\"\",\n",
    "                   font=(\"Time New Roman\",17,))\n",
    "wb_label1.place(x=250,y=330,height=50,width=210)\n",
    "\n",
    "#3----------------------------------------------------------------------------------------\n",
    "temp_label = Label(win,text=\"Temperature\",\n",
    "                   font=(\"Time New Roman\",20,))\n",
    "temp_label.place(x=25,y=400,height=50,width=210)\n",
    "\n",
    "temp_label1 = Label(win,text=\"\",\n",
    "                   font=(\"Time New Roman\",20,))\n",
    "temp_label1.place(x=250,y=400,height=50,width=210)\n",
    "\n",
    "#4---------------------------------------------------------------------------------------\n",
    "ppr_label = Label(win,text=\"Temperatur\",\n",
    "                   font=(\"Time New Roman\",20,))\n",
    "ppr_label.place(x=25,y=470,height=50,width=210)\n",
    "\n",
    "ppr_label1 = Label(win,text=\"\",\n",
    "                   font=(\"Time New Roman\",20,))\n",
    "ppr_label1.place(x=250,y=470,height=50,width=210)\n",
    "\n",
    "\n",
    "done_button = Button(win,text=\"Done\",\n",
    "                   font=(\"Time New Roman\",20,\"bold\"),command=data_get)\n",
    "done_button.place(y=190,height=50,width=100,x=200)\n",
    "\n",
    "\n",
    "win.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f74799b0-952f-4645-baca-798f6e9ae83c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
